version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - fullstack
  server:
    build: .
    entrypoint: ./test.sh
    restart: on-failure
    ports:
      - "5001:5001"
    networks:
      - fullstack
    depends_on:
      - postgres
networks:
  fullstack:
    driver: bridge
